name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Build:
    # Skip build if head commit contains 'skip ci'
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build samples
        run: ./gradlew :sample:assemble

  Upload to Maven:
    environment:
      name: "MavenCentral"

    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Upload library
        run: ./gradlew :vlur:publishAllPublicationsToCentralPortal
